machine:
  environment:
    IMPORT_PATH: "github.com/mycode/GO"
    GOROOT: $GOROOT
    PATH: "/usr/local/go/bin:/usr/local/go/bin:~/.go/bin:${PATH}"
    GOPATH: $GOPATH

dependencies:
  pre:
    - go get github.com/tools/godep

  override:
    - mkdir -p "$GOPATH/src/$IMPORT_PATH"
    - rsync -azC --delete ./ "$GOPATH/src/$IMPORT_PATH/"
    - go get -t -d -v ./...
    - go build -v
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    
    working_directory: /go/src/github.com/mycode/GO
    steps:
      - go test
test:
  pre:
    - go vet ./...

  override:
    - godep go test ./...
