machine:
  environment:
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/go/bin:/usr/local/go/bin:~/.go/bin:${PATH}"
    GOPATH: "/home/amitd92/gocode/github.com/mycode/GO"
    GOBIN: $GOPATH/bin
    TEST_RESULTS: "/home/amitd92/gocode/github.com/mycode/GO/testResults"

dependencies:
  pre:
    - go get github.com/tools/godep
    - go get github.com/stretchr/testify

  override:
    - mkdir -p "$GOPATH"
    - rsync -azC --delete ./ "$GOPATH"
    - go get -t -d -v ./...
    - go build -v
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: mkdir -p {$TEST_RESULTS}
      - run: go get github.com/stretchr/testify
      - run: go get github.com/jstemmer/go-junit-report
      - run: go install src/projectHackerrank/marcCakewalk
      - run: go test ./...
test:
  pre:
    - go vet ./...
    - go test ./...

  override:
    - godep go test ./...
    - go test ./...
