machine:
  environment:
    IMPORT_PATH: "github.com/mycode/GO"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/go/bin:/usr/local/go/bin:~/.go/bin:${PATH}"
    GOPATH: "/home/amitd92/gocode/src/mycode/github.com/mycode/GO"

dependencies:
  pre:
    - go get github.com/tools/godep

  override:
    - mkdir -p "$GOPATH/src/$IMPORT_PATH"
    - rsync -azC --delete ./ "$GOPATH/src/$IMPORT_PATH/"
    - go get -t -d -v ./...
    - go build -v
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: $GOPATH/circleci-work
    steps:
      - checkout
test:
  pre:
    - go vet ./...

  override:
    - godep go test ./...
