machine:
  environment:
    IMPORT_PATH: "github.com/mycode/"
    GOROOT: $GOROOT
    PATH: "/usr/local/go/bin:/usr/local/go/bin:~/.go/bin:${PATH}"
    GOPATH: $GOPATH

dependencies:
  pre:
    - go get github.com/tools/godep

  override:
    - mkdir -p "$GOPATH/src/$IMPORT_PATH"
    - rsync -azC --delete ./ "$GOPATH/src/$IMPORT_PATH/"
    - go get -t -d -v ./...
    - go build -v
jobs:
  build:
    steps:
      - run: make test

test:
  pre:
    - go vet ./...

  override:
    - godep go test ./...
